#
# Basic image processing
#
from rsf.proj import *
import wplot

par = dict(
    nz=512, dz=1, oz=0, lz='z', uz='m',
    nx=512, dx=1, ox=0, lx='x', ux='m',
    height=10
    )
wplot.param(par)

# ------------------------------------------------------------
# Download the input data file
Fetch('lena.img','imgs')

# ------------------------------------------------------------
# Create RSF header
Flow('lena.hdr','lena.img',
     'echo n1=512 n2=513 in=$SOURCE data_format=native_uchar',
     stdin=0)

# Convert to floating point and window out first trace
Flow('lena','lena.hdr',
     'dd type=float | window f2=1 | transp')

# Smooth the image
Flow('lsmo','lena','smooth rect1=10 rect2=10')

# Display original image
Result('lena',wplot.igrey2d('bias=128',par))

#Display the colored image
Result('lcol','lena',wplot.igrey2d('bias=30 color=j',par))

# ------------------------------------------------------------
# Bandpass processing
Flow('bpas','lena','bandpass flo=0.1')

# Display processed image
Result('bpas',wplot.igrey2d('pclip=99',par))

# Wrap up
End()
