#
# "Shot-record imaging
#
from rsf.proj import *
import sigsbee,geom,awe,wplot

# ------------------------------------------------------------
par=sigsbee.paramwin() # Sigsbee2A parameters
wplot.param(par)       # plotting parameters
awe.param(par)    
ne=3 # number of experiments

geom.horizontal2d('tt',par['oz']+10*par['dz'],'',par)

# ------------------------------------------------------------
for ie in range(ne):
       etag='%d'%ie

       # source coordinates
       # xsou=10.9-ie*2.0
       xsou=10.0-ie*2.0
       geom.point2d('ss'+etag,xsou,par['oz']+10*par['dz'],'',par)
       Plot('ss'+etag,wplot.ssplot2d('',par))

       # receiver coordinatess
       # Flow('rr'+etag,'tt','window min2=%g max2=%g j2=5'%(xsou+0.1,xsou+3.1))
       Flow('rr'+etag,'tt','window min2=%g max2=%g j2=4'%(xsou+0.1,xsou+4.0))
       Plot('rr'+etag,wplot.rrplot2d('plotfat=10',par)) 

# overlay sources
Plot('ss',['ss%d'%ie for ie in range(ne)],'Overlay')
 
# ------------------------------------------------------------
# get velocity
sigsbee.getstrvelwin('vstr',par)
Flow(  'velo','vstr','smooth rect1=25 rect2=25 repeat=1')
Plot(  'velo',wplot.igrey2d('mean=y',par))
Result('velo',['velo','ss'],'Overlay')

# get density
sigsbee.getreflectwin('rflc',par)
Flow('dens','rflc','scale axis=123 | scale rscale=0.5 | add add=1')
Flow('dcon','dens','math output=1')      # constant density
Plot(  'dens',wplot.igrey2d('mean=y',par))

for ie in range(ne):
       etag='%d'%ie
       Result('velo'+etag,['velo','ss'+etag,'rr'+etag],'Overlay')
       Result('dens'+etag,['dens','ss'+etag,'rr'+etag],'Overlay')

# ------------------------------------------------------------
# construct wavelet
awe.wavelet('wav',10,'',par)     

# plot wavelet
Result('wav','window |'+ wplot.waveplot('',par)) 

# ------------------------------------------------------------
for ie in range(ne):
       etag='%d'%ie
       
       # run FD modeling
       awe.awefd2d('dtmp'+etag,'wfld'+etag,'wav','velo','dens','ss'+etag,'rr'+etag,'fsrf=y',par)
       awe.awefd2d('ddir'+etag,'wcon'+etag,'wav','velo','dcon','ss'+etag,'rr'+etag,'fsrf=y',par)
       Flow('data'+etag,['dtmp'+etag,'ddir'+etag],'add scale=1,-1 ${SOURCES[1]}')

       # plot data
       Result('data'+etag,
              'window j2=4 | transp|' + wplot.dgrey2d('pclip=99',par))
       Result('wigl'+etag,'data'+etag,
              'window j2=4 | transp|' + wplot.dwigl2d('pclip=99',par))

       # plot wavefield frames
       awe.wom('wflm'+etag,'wfld'+etag,'dens',1,par)
       Flow('wbyt'+etag,'wflm'+etag,'byte gainpanel=a pclip=99')
       for i in range( int((par['nt']-1)/par['jsnap']) ):
              ftag = '-%02d'%i
              Plot(   'wfld'+etag+ftag,'wbyt'+etag,wplot.ifrm2d(i,'',par))
              Result( 'wfld'+etag+ftag,
                     ['wfld'+etag+ftag,'ss'+etag,'rr'+etag],'Overlay')

       # run FD migration
       awe.cicmigCD('imag'+etag,        # image
                    'wav',              # wavelet
                    'ss'+etag,          # source coordinates
                    'data'+etag,        # data
                    'rr'+etag,          # receiver coordinates
                    'velo',             # velocity
                    'jsnap=4 nbuf=100', # optional parameters
                    par)

       # plot image
       Plot(  'imag'+etag,
              'bandpass flo=2 |'
              + wplot.igrey2d('pclip=99',par))
       Result('imag'+etag,['imag'+etag,'ss'+etag,'rr'+etag],'Overlay')

# ------------------------------------------------------------
# stack images
Flow('imag',['imag%d'%ie for ie in range(ne)],
     'cat axis=3 space=n ${SOURCES[1:%d]} | stack axis=3'%ne)
Plot(  'imag',
       'bandpass flo=2 |'
       + wplot.igrey2d('pclip=99',par))
Result('imag',['imag','ss'],'Overlay')
# ------------------------------------------------------------
End()
